{
  "targets":[
    {
        "target_name":"hello",
        "sources":[
            "pca9685.c",
            "servo.c",
            "hello.cc"
        ],
        "conditions":[
            ['OS=="linux"',{
                "libraries":["-lwiringPi"]
            }]
        ]
    }
  ]
}
